name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: ["22.x"]
        platform: [ubuntu-latest]
    name: Node v${{matrix.node}} ((${{matrix.platform}}))
    runs-on: ${{matrix.platform}}
    defaults:
      run:
        working-directory: packages/ai-bom-visualizer
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: install root dependencies
        run: npm install
        working-directory: .
      - name: build root HTML template
        run: npm run build:template
        working-directory: .
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: build project
        run: npm run build
      - name: run tests
        run: npm run test
      - name: coverage
        uses: codecov/codecov-action@v5
        if: github.actor != 'dependabot[bot]'
        with:
          fail_ci_if_error: true
          verbose: false
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: packages/ai-bom-visualizer
        env:
          CI: true

  release-preview:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: packages/ai-bom-visualizer
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: install root dependencies
        run: npm install
        working-directory: .
      - name: build root HTML template
        run: npm run build:template
        working-directory: .
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: release preview with pkr-pr-new
        run: npx pkg-pr-new publish
